
FROM golang:1.18-alpine

WORKDIR /usr/app



COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY custom-controller/ .

RUN CGO_ENABLED=0 go build -ldflags '-s' -o bin/lets-expose *.go

#---

FROM scratch
COPY --from=0 /usr/app .
ENTRYPOINT ["./bin/lets-expose"]