apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-expose-sa
  namespace: lets-expose
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lets-expose
  name: auto-expose-role
rules:
- apiGroups: ["networking.k8s.io"] # "" indicates the core API group
  resources: ["ingresses","ingresses/status", "networkpolicies"]
  verbs: ["get", "watch", "list","create", "update", "patch", "delete"]
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["get", "watch", "list","create", "update", "patch", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "watch", "list","create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: auto-expose-rb
  namespace: lets-expose
subjects:
- namespace: lets-expose 
  kind: ServiceAccount
  name: auto-expose-sa
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: auto-expose-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auto-expose-dep
  name: auto-expose-dep
  namespace: lets-expose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-expose
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auto-expose
    spec:
      serviceAccountName: auto-expose-sa
      containers:
      - image: mabhi2ic/auto-expose:v0.1.0
        name: auto-expose
        resources: {}
status: {}
---