apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    # custom: nginx-deploy
    app: kubernetes-test
  name: nginx-one
  namespace: lets-expose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-one
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-one
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http-web-svc
        resources: {}
status: {}
